# My Daily Routine Printer

print("\n")
print("*********************************************************************************************")
print("                           MY DAILY ROUTINE!!! (for school: mon-fri) ") 
print("*********************************************************************************************\n")
print("1: Wake up at 6:20 P.M\n") 
print("2: Eat breakfast\n") 
print("3: Brush my teeth\n")
print("4: Get ready for school( change clothes( if needed), comb hair, etc)\n")
print("5: Use toilettrees (lotion, deodorant, etc)\n")
print("6: Grab backpack and lunch box\n")
print("7: Be ready for my carpoolers to come pick me up & have FUN AT SCHOOL!!!!!!!!!!!!!!!!!! \n") 
print("My total study time per day is about 30 minutes\n ")
print("Total study time in a week :", 0.5 * 7, "hours\n"  )